# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDFWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDFWidget(object):
    def setupUi(self, PDFWidget):
        PDFWidget.setObjectName("PDFWidget")
        PDFWidget.resize(839, 986)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PDFWidget.sizePolicy().hasHeightForWidth())
        PDFWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PDFWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.reading_area = QtWidgets.QLabel(PDFWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.reading_area.sizePolicy().hasHeightForWidth())
        self.reading_area.setSizePolicy(sizePolicy)
        self.reading_area.setMinimumSize(QtCore.QSize(720, 960))
        self.reading_area.setText("")
        self.reading_area.setAlignment(QtCore.Qt.AlignCenter)
        self.reading_area.setObjectName("reading_area")
        self.verticalLayout.addWidget(self.reading_area)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(PDFWidget)
        QtCore.QMetaObject.connectSlotsByName(PDFWidget)

    def retranslateUi(self, PDFWidget):
        _translate = QtCore.QCoreApplication.translate
        PDFWidget.setWindowTitle(_translate("PDFWidget", "Form"))
